name: Python Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Specify your Python version here

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask
        pip install coverage

    - name: Show directories
      run: |
        echo "Listing all the directories in root"
        ls -R

    - name: Run tests
      run: |
        coverage run -m unittest discover -s tests
        coverage report
      env:
        PYTHONPATH: src
